application: rdf-translator
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /parse
  script: main.py

- url: /
  static_files: index.html
  upload: index\.html

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  
- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt
  
- url: /humans\.txt
  static_files: humans.txt
  upload: humans\.txt